name: Testes Automatizados

on:
  push:
    branches: 
      - main
      - feature/*
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes External (GraphQL)
        run: npm run test.external

      - name: Rodar testes Controller (REST)
        run: npm run test.controller

      - name: Gerar relatório de teste (mochawesome)
        run: |
          npm install mochawesome mochawesome-merge mochawesome-report-generator --save-dev
          npx mochawesome-merge ./mochawesome-report/*.json > mochawesome.json
          npx marge mochawesome.json --reportDir ./mochawesome-report --reportTitle "Relatório de Testes"

      - name: Publicar relatório como artifact
        uses: actions/upload-artifact@v3
        with:
          name: Relatório-de-Testes
          path: ./mochawesome-report
